### ISSUE TITLE
Keep getting Failed to connect to AE

### ISSUE THREAD

**Issue by DESIGNfromWITHIN** [google/sketch2ae#25]
I am trying to export my Figma frame (Windows 10) to After Effects (17.5.0 using Creative Cloud latest update)
Using AEUX_0.7.5a

But keep getting: `Failed to connect to AE`
After Effects is running all normal.

What can I try?

![failed](https://user-images.githubusercontent.com/725851/96884425-c7c75c00-1481-11eb-8a57-9a6e2fa4b6f0.png)

**Comment by adamplouff** [comment]
1. Check that the Ae extension is installed and Ae is open. The panel doesn't have to be open in Ae to work, but double check that it will open. 

2. Try a system restart. Sometimes the connection system gets a little tired and restarting can clear out the cobwebs. 

3. If that doesn't work, there might be a problem with reading the art (and there isn't a check for it). What happens if you try to send a simple rectangle? If that works then the apps are talking to one another and there is a problem with layers. Share a copy of the problematic layer(s) with adamplouff@google.com

Any luck?

**Comment by robertabelf** [comment]
I have the same problem on my Mac using Figma. When I try to export the frame, it shows a "Failed to connect to Ae". I have After Effects CC2018 installed, and when I open the AEUX plugin, I only see an empty white panel. I also tried the manual installation, but still nothing. Any idea on what's wrong?

**Comment by adamplouff** [comment]
@robertabelf AEUX supports CC2019+. Try updating to get the Ae panel working and that should allow for a working connection between apps.
